import { anthropic } from "@ai-sdk/anthropic";
import {
  convertToModelMessages,
  stepCountIs,
  streamText,
  tool,
  type UIMessage,
} from "ai";
import { z } from "zod";
import { dataUrlToBytes, generate3dFromBytes } from "@/lib/generate3d";
import { editGarmentImage, readPublicGeneratedFile } from "@/lib/edit-image";

export const maxDuration = 600;
export const runtime = "nodejs";

const MODEL_ID = process.env.ANTHROPIC_MODEL ?? "claude-sonnet-4-5";

const SYSTEM_PROMPT = `You are Garmentor, an assistant that helps users turn photos of garments into measurement-accurate 3D models, iterate on the design via image edits, and eventually produce flat sewing patterns (DXF) by drawing seam lines on the mesh.

The 3D model is generated by Hunyuan3D-2 from a single image. The output mesh faithfully reproduces whatever shape the image shows — it cannot invent volume that is not visible. This means input photo quality directly determines whether the resulting mesh can be used for real-world measurement.

Image quality ranking, best to worst, for garment 3D reconstruction:
1. Ghost-mannequin shot — garment shaped on an invisible form, photographed straight-on or at a slight 3/4 angle. Produces a properly volumetric mesh with realistic drape, sleeve curvature, and body shape. This is the only input type suitable for accurate measurement.
2. Worn-on-person shot, plain background, neutral pose, arms slightly away from body. Good volume but the resulting mesh will include body shape; you will need to subtract that mentally.
3. Mannequin shot (visible mannequin). Decent volume, but the mannequin geometry will be baked into the mesh.
4. Flat lay (garment laid flat on a surface). Produces a flat, two-dimensional mesh with no drape or volume — unsuitable for measurement. Strongly discourage this.
5. Hanger shot. Distorted shoulders and collapsed sides — poor results.

Tools available:
- \`edit_garment_image\` — given a text instruction (e.g. "change patch pockets to welt pockets", "add a chest pocket", "make the collar a notch lapel"), produces an edited mockup of the garment photo using Qwen-Image-Edit-2509. Use this when the user wants to modify the design rather than reconstruct the photo as-is. Operates on the most recently attached or edited image by default.
- \`generate_3d_model\` — generates a 3D mesh (.glb) from an image. By default uses the most recently attached image. After an \`edit_garment_image\` call, pass the returned \`imageUrl\` so the mesh is built from the edited mockup, not the original photo.

Behavior:
- When the user attaches an image, first identify the garment type (jacket, shirt, dress, pants, etc.) and classify the shot type using the ranking above. State both in one short sentence.
- If the user only wants the photo reconstructed in 3D and the shot is type 1 or 2, call \`generate_3d_model\` directly. Type 3: proceed with a brief warning. Type 4 or 5: explain the issue and ask for a better photo or explicit confirmation before proceeding.
- If the user wants to MODIFY the design (add pockets, change collar, swap construction details, recolor, etc.), the workflow is: (1) call \`edit_garment_image\` with a clear, concrete instruction, (2) briefly show the user the mockup that comes back and ask if it looks right, (3) only after the user approves, call \`generate_3d_model\` with the edited \`imageUrl\` to rebuild the mesh. Do not chain into 3D regen automatically — the user should approve the mockup first.
- Multiple edits can be stacked: each \`edit_garment_image\` call returns a new image URL that can be the source for the next edit if the user wants further changes.
- For accurate real-world scaling, ask the user once for a known reference dimension (e.g., "back length 72 cm" or "chest width 56 cm flat") so the unitless mesh can be scaled later. If they decline, proceed without it.
- After any tool returns, briefly summarize the result in one or two sentences. The image viewer and 3D viewer are rendered in the UI from the tool results; do not try to embed them yourself.
- If the user has not attached any image yet, ask them to attach one before calling either tool.
- Be concise. Seam drawing happens in the workspace pane; cutting and DXF export are coming in later phases — do not claim those are done.`;

type ImageBlob = { bytes: Uint8Array; mediaType: string };

function extractLatestImage(messages: UIMessage[]): ImageBlob | null {
  for (let i = messages.length - 1; i >= 0; i--) {
    const msg = messages[i];
    if (msg.role !== "user") continue;
    const parts = msg.parts ?? [];
    for (let j = parts.length - 1; j >= 0; j--) {
      const part = parts[j] as {
        type: string;
        url?: string;
        mediaType?: string;
      };
      if (
        part.type === "file" &&
        part.url?.startsWith("data:") &&
        part.mediaType?.startsWith("image/")
      ) {
        return dataUrlToBytes(part.url);
      }
    }
  }
  return null;
}

async function resolveImage(
  imageUrl: string | undefined,
  fallback: ImageBlob | null,
): Promise<ImageBlob | null> {
  if (imageUrl) {
    if (imageUrl.startsWith("data:")) return dataUrlToBytes(imageUrl);
    if (imageUrl.startsWith("/generated/")) {
      return await readPublicGeneratedFile(imageUrl);
    }
    return null;
  }
  return fallback;
}

export async function POST(req: Request) {
  const { messages }: { messages: UIMessage[] } = await req.json();
  const latestImage = extractLatestImage(messages);

  const result = streamText({
    model: anthropic(MODEL_ID),
    system: SYSTEM_PROMPT,
    messages: await convertToModelMessages(messages),
    stopWhen: stepCountIs(4),
    tools: {
      generate_3d_model: tool({
        description:
          "Generate a 3D model (.glb) from a garment image. By default uses the most recently attached user image. Pass `imageUrl` (returned by edit_garment_image) to build the mesh from an edited mockup instead. Returns a URL to the generated GLB which the UI renders in an interactive viewer.",
        inputSchema: z.object({
          description: z
            .string()
            .describe(
              "Short description of what the image contains (e.g. 't-shirt, front view'). Used for logging only.",
            ),
          imageUrl: z
            .string()
            .optional()
            .describe(
              "Optional. URL of a previously edited image to use as the source (e.g. the `imageUrl` returned by edit_garment_image). If omitted, uses the most recently attached user image.",
            ),
        }),
        execute: async ({ description, imageUrl }) => {
          const source = await resolveImage(imageUrl, latestImage);
          if (!source) {
            return {
              ok: false as const,
              error: imageUrl
                ? `Could not load source image at ${imageUrl}.`
                : "No image found in the conversation. Ask the user to attach a photo and try again.",
            };
          }
          try {
            const out = await generate3dFromBytes(
              source.bytes,
              source.mediaType,
            );
            return {
              ok: true as const,
              glbUrl: out.url,
              id: out.id,
              bytes: out.bytes,
              description,
              sourceImageUrl: out.sourceImageUrl,
            };
          } catch (err) {
            const message = err instanceof Error ? err.message : String(err);
            return { ok: false as const, error: message };
          }
        },
      }),
      edit_garment_image: tool({
        description:
          "Edit the garment photo with a natural-language instruction (e.g. 'change patch pockets to welt pockets', 'add a chest pocket', 'make the collar a notch lapel'). Uses Qwen-Image-Edit-2509. Returns a new image URL that the UI shows inline. Always show the result to the user and get approval before chaining into generate_3d_model.",
        inputSchema: z.object({
          instruction: z
            .string()
            .min(3)
            .describe(
              "Concrete edit instruction. Be specific about what to change and what to keep. Example: 'Change the two patch pockets on the chest to welt pockets, keep the rest of the jacket identical.'",
            ),
          sourceImageUrl: z
            .string()
            .optional()
            .describe(
              "Optional. URL of an earlier edited image to edit further (returned by a previous edit_garment_image call). If omitted, uses the most recently attached user image.",
            ),
        }),
        execute: async ({ instruction, sourceImageUrl }) => {
          const source = await resolveImage(sourceImageUrl, latestImage);
          if (!source) {
            return {
              ok: false as const,
              error: sourceImageUrl
                ? `Could not load source image at ${sourceImageUrl}.`
                : "No image found in the conversation. Ask the user to attach a photo and try again.",
            };
          }
          try {
            const out = await editGarmentImage(
              source.bytes,
              source.mediaType,
              instruction,
            );
            return {
              ok: true as const,
              imageUrl: out.url,
              id: out.id,
              bytes: out.bytes,
              instruction,
            };
          } catch (err) {
            const message = err instanceof Error ? err.message : String(err);
            return { ok: false as const, error: message };
          }
        },
      }),
    },
  });

  return result.toUIMessageStreamResponse({
    onError: (err) => {
      if (err instanceof Error) return err.message;
      return typeof err === "string" ? err : "Unknown error";
    },
  });
}
